#!/usr/bin/env python3
# =============================================================================
# ai_enricher.py — Automatically Runs AI Deep Dive on Multibagger Candidates
# =============================================================================
# Reads the output/multibagger_candidates.xlsx file generated by the hunter,
# downloads the latest presentation for each ticker, runs FinBERT on it,
# and updates the Excel file with the AI's net sentiment score and top quotes.
# =============================================================================

import os
import pandas as pd
from rich.console import Console
from rich.panel import Panel

import requests_cache
requests_cache.install_cache('market_data_cache', expire_after=86400)

# We import the FinBERT analyzer logic directly
from finbert_analyzer import analyze_document_with_finbert

console = Console()

import argparse

def enrich_candidates():
    parser = argparse.ArgumentParser(description="Run FinBERT AI on an Excel list of candidates.")
    parser.add_argument("--input", default="output/multibagger_candidates.xlsx", help="Path to input Excel file.")
    parser.add_argument("--limit", type=int, default=None, help="Max number of companies to analyze (e.g. 50)")
    args = parser.parse_args()
    
    path = args.input
    if not os.path.exists(path):
        console.print(f"[yellow]No candidates file found at {path}[/yellow]")
        return

    df = pd.read_excel(path)
    if df.empty:
        console.print("[yellow]The candidates file is empty. Nothing to enrich.[/yellow]")
        return
        
    if args.limit and len(df) > args.limit:
        console.print(f"[cyan]Limiting AI analysis to the top {args.limit} candidates...[/cyan]")
        df = df.head(args.limit).copy()

    console.print(Panel.fit(
        f"[bold green]🤖 AI Enrichment Pipeline[/bold green]\n"
        f"[dim]Running FinBERT deep dive on {len(df)} candidates...[/dim]"
    ))

    sentiments = []
    pos_quotes = []
    
    for ticker in df['ticker']:
        console.print(f"\n[bold magenta]Processing {ticker}...[/bold magenta]")
        
        # We prefer the presentation for forward looking statements, fallback to transcript
        try:
            # 1. Try Presentation
            res = analyze_document_with_finbert(ticker, "presentation")
            
            # 2. If no presentation, try Transcript
            if not res:
                console.print(f"[dim]No presentation found for {ticker}, trying transcript...[/dim]")
                res = analyze_document_with_finbert(ticker, "transcript")
            
            if res:
                sentiments.append(res['net_sentiment'])
                # Join the top 3 quotes so it fits in a single Excel cell
                quotes_str = " | ".join(res['positive_top'][:3])
                pos_quotes.append(quotes_str)
            else:
                sentiments.append(None)
                pos_quotes.append("No document found in last 12 months")
        except Exception as e:
            console.print(f"[red]Error analyzing {ticker}: {e}[/red]")
            sentiments.append(None)
            pos_quotes.append(f"Error: {str(e)}")

    # Add the new AI columns to the dataframe
    df['AI_Net_Sentiment_%'] = sentiments
    df['AI_Top_Positive_Quotes'] = pos_quotes

    # Sort the final file so the absolute best stocks are at the top
    # Priority 1: PEG Ratio (Cheapest growth first)
    # Priority 2: AI Sentiment
    if 'Composite_Factor_Score' in df.columns:
        df = df.sort_values(by=['Composite_Factor_Score', 'AI_Net_Sentiment_%'], ascending=[False, False])
    else:
        df = df.sort_values(by=['PEG_Ratio', 'AI_Net_Sentiment_%'], ascending=[True, False], na_position='last')
    
    # Save it back
    df.to_excel(path, index=False)
    console.print(f"\n[bold green]✅ AI Enrichment Complete! Excel file updated at {path}[/bold green]")

if __name__ == "__main__":
    enrich_candidates()
