#!/usr/bin/env python3
# =============================================================================
# ai_enricher.py — Automatically Runs AI Deep Dive on Multibagger Candidates
# =============================================================================
# Reads the output/multibagger_candidates.xlsx file generated by the hunter,
# downloads the latest presentation for each ticker, runs FinBERT on it,
# and updates the Excel file with the AI's net sentiment score and top quotes.
# =============================================================================

import os
import pandas as pd
from rich.console import Console
from rich.panel import Panel

# We import the FinBERT analyzer logic directly
from finbert_analyzer import analyze_document_with_finbert

console = Console()

def enrich_candidates():
    path = "output/multibagger_candidates.xlsx"
    if not os.path.exists(path):
        console.print("[yellow]No candidates file found. Please run multibagger_hunter.py first.[/yellow]")
        return

    df = pd.read_excel(path)
    if df.empty:
        console.print("[yellow]The candidates file is empty. Nothing to enrich.[/yellow]")
        return

    console.print(Panel.fit(
        f"[bold green]🤖 AI Enrichment Pipeline[/bold green]\n"
        f"[dim]Running FinBERT deep dive on {len(df)} surviving multibagger candidates...[/dim]"
    ))

    sentiments = []
    pos_quotes = []
    
    for ticker in df['ticker']:
        console.print(f"\n[bold magenta]Processing {ticker}...[/bold magenta]")
        
        # We prefer the presentation for forward looking statements, fallback to transcript
        try:
            # 1. Try Presentation
            res = analyze_document_with_finbert(ticker, "presentation")
            
            # 2. If no presentation, try Transcript
            if not res:
                console.print(f"[dim]No presentation found for {ticker}, trying transcript...[/dim]")
                res = analyze_document_with_finbert(ticker, "transcript")
            
            if res:
                sentiments.append(res['net_sentiment'])
                # Join the top 3 quotes so it fits in a single Excel cell
                quotes_str = " | ".join(res['positive_top'][:3])
                pos_quotes.append(quotes_str)
            else:
                sentiments.append(None)
                pos_quotes.append("No document found in last 12 months")
        except Exception as e:
            console.print(f"[red]Error analyzing {ticker}: {e}[/red]")
            sentiments.append(None)
            pos_quotes.append(f"Error: {str(e)}")

    # Add the new AI columns to the dataframe
    df['AI_Net_Sentiment_%'] = sentiments
    df['AI_Top_Positive_Quotes'] = pos_quotes

    # Sort the final file so the absolute best stocks are at the top
    # Priority 1: High Trajectory Score
    # Priority 2: High AI Sentiment
    df = df.sort_values(by=['trajectory_score', 'AI_Net_Sentiment_%'], ascending=[False, False])
    
    # Save it back
    df.to_excel(path, index=False)
    console.print(f"\n[bold green]✅ AI Enrichment Complete! Excel file updated at {path}[/bold green]")

if __name__ == "__main__":
    enrich_candidates()
